# ---------------------------------------------------------
#           COLLISION AVOIDANCE CONFIGURATION FILE            
# ---------------------------------------------------------

#TOTAL number of robots
number_of_robots: 2

# NED origin definition
ned_origin_lat: 39.543330
ned_origin_lon: 2.377940

# Area of the square of exploration (m^2)
area_of_exploration: 400

# Collision avoidance algorith to use {stop&wait, PF}
collision_algorithm: 'PF'
